//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noteapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesSet
    {
        public int CD_Notes { get; set; }
        public string CH_Name { get; set; }
        public string CH_Description { get; set; }
        public System.DateTime DT_Creation { get; set; }
    }
}
